# Generated by Django 4.2.5 on 2023-09-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Area',
        ),
    ]
