# Generated by Django 4.2.5 on 2023-09-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_location_area'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='Area',
        ),
    ]
