# Generated by Django 4.2.5 on 2023-09-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_user_businesses'),
        ('user', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('is_businessman', 'Is Businessman'), ('is_location_owner', 'Is Location Owner')]},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
